name: ics file

on:
  push:
  pull_request:
  schedule:
    - cron: '15 6 1 * *' # on day 1 of each month

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate ics
        run: |
          python AuburnCalendar.py
      - name: Upload ics
        uses: actions/upload-artifact@v3
        with:
          name: ics 
          path: AuburnCalendar.ics
